### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by ThomasCornillet** [ThomasCornillet/south-park#1]
Depuis que j'ai mis le repo sur github, ça plante après l'entrée du nombre d'épisode.

reproduction :
[thomas@localhost South Park]$ ./south_park.py 
Bienvenue dans la sélection aléatoire d'un épisode de South Park

Nous allons tout d'abord sélectionner une saison, puis un épisode dans cette saison.

Sélection de la saison
Quelle est la première saison à votre disposition ?17
Quelle est la dernière saison à votre disposition ?12
Traceback (most recent call last):
  File "./south_park.py", line 35, in <module>
    saison_choix = choix_saison(saison_min,saison_max)
  File "./south_park.py", line 25, in choix_saison
    return randint(a,b)
  File "/usr/lib64/python3.5/random.py", line 218, in randint
    return self.randrange(a, b+1)
  File "/usr/lib64/python3.5/random.py", line 196, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (17,13, -4)

**Comment by ThomasCornillet** [comment]
en fait c'est normal, mauvaise manipe :  l'interval pour la saison est "corrompu", le n° de dernière saison est inférieur à celui de la première saison

ça n'empêche qu'il faut prévoir ce cas
